### ISSUE TITLE
Post image Never work with swift 2.1

### ISSUE THREAD

**Issue by Mahadev77** [devedup/FlickrKit#49]
Please improve it for swift 2.1

**Comment by devedup** [comment]
Would you stop opening unspecific issues like this. 

Firstly, you should be using swift 2.3 or swift 3.0. 

You need to use StackOverflow, post your code, what you've tried, what errors you're getting, maybe the debug console output etc.... We can't guess what the problem is without this information.

**Comment by Mahadev77** [comment]
Thank you for your valuable suggestions
